### ISSUE TITLE
Issue with enabling this plugin as an external plugin for coredns

### ISSUE THREAD

**Issue by quentinkhoo** [coredns/policy#37]
As the title suggests, I'm struggling to enable this as an external plugin in coredns even after following the instructions highlighted in the [README.md](https://github.com/coredns/policy#external-plugin).

First of all I'm using `coredns` on `branch v1.9.3` and I'm running this on a `macOS Monterey v12.4`:
![image](https://user-images.githubusercontent.com/33711159/182126083-a17a2d44-0715-4407-9bb4-18509d1948ca.png)

I followed the instructions as detailed below:

Update `plugin.cfg`:
![image](https://user-images.githubusercontent.com/33711159/182125530-eca2afd7-d9b5-4828-a3fc-3eca5015e278.png)

Run `go get github.com/coredns/policy`
Run `go generate`
Run `go build` (and it's at this step i get the error `no required module provides package github.com/coredns/policy; to add it: go get github.com/coredns/policy`

![image](https://user-images.githubusercontent.com/33711159/182125758-f11df7ed-6cf2-49d8-aa5f-f58fa8207d91.png)

However, I am able to successfully compile other external plugins like [finalize](https://github.com/tmeckel/coredns-finalizer) and successfully compile a coredns binary out of it as shown below:
`plugin.cfg`:
![image](https://user-images.githubusercontent.com/33711159/182127146-7369bc2e-d193-4966-905b-2ae5cbb1fdca.png)
List of coredns plugins:
![image](https://user-images.githubusercontent.com/33711159/182127225-51d27aea-3cd2-48f1-951f-17d52dfd11d1.png)

Any advice would be appreciated thank you!

**Comment by chrisohaver** [comment]
This repo contains more than one plugin, so the full path to the individual plugins includes the `plugin` directory.
e.g. `firewall:github.com/coredns/policy/plugin/firewall`

I'll add this example to the README, since it's not obvious.

**Comment by quentinkhoo** [comment]
Thank you @chrisohaver ! I can verify that this works indeed (an additional `go get github.com/coredns/policy/plugin/firewall/policy@v0.0.0-20220801124252-80b8eac97936` was required but that was all)
![image](https://user-images.githubusercontent.com/33711159/182304382-8b709d4b-126b-4fbb-a34f-b7d9a2d9bc2e.png)

![image](https://user-images.githubusercontent.com/33711159/182304543-92fdf1bb-f3b1-4b72-998a-25186f257817.png)
